services:
    postgres:
      image: postgres:15
      container_name: social-postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: social
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin_container
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: sina@s.com
        PGADMIN_DEFAULT_PASSWORD: 123456
      ports:
        - "5050:80"
      depends_on:
        - postgres

volumes:
  pgdata: