services:
    postgres:
      image: postgres:15
      container_name: social-postgres
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: social
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: